# Generated by Django 5.1.7 on 2025-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_user_suppliers_user_alter_order_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='username',
            field=models.TextField(default='None'),
        ),
    ]
