# Generated by Django 5.1.7 on 2025-03-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_order_user_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='url',
            field=models.TextField(default='None'),
        ),
    ]
