# Generated by Django 5.1.7 on 2025-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_suppliers_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_state',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default='None'),
        ),
    ]
