# Generated by Django 5.2 on 2025-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_order_payment_terms_order_payment_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/files/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default='None'),
        ),
        migrations.AddField(
            model_name='order',
            name='files',
            field=models.ManyToManyField(to='users.orderfile'),
        ),
    ]
