# Generated by Django 5.1.7 on 2025-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_order_payment_terms_order_payment_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default='None'),
        ),
    ]
