# Generated by Django 5.2 on 2025-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_orderfile_order_created_at_alter_order_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.TextField(default='Обычный'),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
