# Generated by Django 5.2 on 2025-04-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_order_options_remove_order_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.order'),
            preserve_default=False,
        ),
    ]
