# Generated by Django 5.2 on 2025-04-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_orderfile_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfile',
            old_name='order',
            new_name='order_id',
        ),
    ]
