# Generated by Django 5.2 on 2025-04-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_order_id_orderfile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
