# Generated by Django 5.1.7 on 2025-03-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='None')),
                ('end_date', models.DateField(default='None')),
                ('titles', models.TextField(default='None')),
                ('text', models.TextField(default='None')),
                ('level_importance', models.CharField(max_length=40)),
            ],
        ),
    ]
