# Generated by Django 5.1.7 on 2025-03-25 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='titles',
            field=models.TextField(),
        ),
    ]
