# Generated by Django 5.1.7 on 2025-03-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0004_alter_articles_end_date_alter_articles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user',
        ),
    ]
