# Generated by Django 5.1.7 on 2025-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_suppliersdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.TextField()),
                ('payment_terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='SuppliersData',
        ),
    ]
